/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediaplayer;


/**
 *
 * @author gisleude
 */
public class JanelaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JanelaUser
     */
    public JanelaAdmin() {
        initComponents();
        this.l_q_volume.setText(Integer.toString(this.s_volume.getValue())+"%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_music = new javax.swing.JPanel();
        l_music = new javax.swing.JLabel();
        l_artist = new javax.swing.JLabel();
        l_album = new javax.swing.JLabel();
        l_year = new javax.swing.JLabel();
        t_music = new javax.swing.JTextField();
        t_artist = new javax.swing.JTextField();
        t_album = new javax.swing.JTextField();
        t_year = new javax.swing.JTextField();
        s_volume = new javax.swing.JSlider();
        l_volume = new javax.swing.JLabel();
        b_play = new javax.swing.JButton();
        b_pause = new javax.swing.JButton();
        b_stop = new javax.swing.JButton();
        l_q_volume = new javax.swing.JLabel();
        l_music_options = new javax.swing.JLabel();
        b_remove_music = new javax.swing.JButton();
        b_move_music = new javax.swing.JButton();
        l_atual_music = new javax.swing.JLabel();
        p_list_music = new javax.swing.JPanel();
        painel_lista = new javax.swing.JScrollPane();
        lista_playlists = new javax.swing.JList<>();
        l_list_playlists = new javax.swing.JLabel();
        l_list_musics = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_musicas = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        barra_menu = new javax.swing.JMenuBar();
        m_options = new javax.swing.JMenu();
        mI_add_music = new javax.swing.JMenuItem();
        mI_remove_music = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mI_add_playlist = new javax.swing.JMenuItem();
        mI_remove_playlist = new javax.swing.JMenuItem();
        mI_promove_user = new javax.swing.JMenuItem();
        mI_add_user = new javax.swing.JMenuItem();
        mI_remove_user = new javax.swing.JMenuItem();
        o_exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediaPlayer - Administrador");
        setResizable(false);

        l_music.setText("Música:");

        l_artist.setText("Artista:");

        l_album.setText("Albúm:");

        l_year.setText("Ano:");

        t_music.setEditable(false);

        t_artist.setEditable(false);

        t_album.setEditable(false);

        t_year.setEditable(false);

        l_volume.setText("Volume:");

        b_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/play.png"))); // NOI18N
        b_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_playActionPerformed(evt);
            }
        });

        b_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pause.png"))); // NOI18N

        b_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stop.png"))); // NOI18N

        l_music_options.setText("Opções para a música");

        b_remove_music.setText("Tirar da Playlist");
        b_remove_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_remove_musicActionPerformed(evt);
            }
        });

        b_move_music.setText("Mover de Playlist");
        b_move_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_move_musicActionPerformed(evt);
            }
        });

        l_atual_music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/megaphone_24.png"))); // NOI18N
        l_atual_music.setText("Música Atual");

        javax.swing.GroupLayout p_musicLayout = new javax.swing.GroupLayout(p_music);
        p_music.setLayout(p_musicLayout);
        p_musicLayout.setHorizontalGroup(
            p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                        .addComponent(l_q_volume)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                        .addComponent(l_atual_music)
                        .addGap(95, 95, 95))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                .addComponent(l_volume)
                .addGap(3, 3, 3)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_musicLayout.createSequentialGroup()
                        .addComponent(s_volume, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(p_musicLayout.createSequentialGroup()
                        .addComponent(b_play, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(p_musicLayout.createSequentialGroup()
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_musicLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_musicLayout.createSequentialGroup()
                                .addComponent(b_remove_music)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_move_music)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(t_album, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_year, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_artist)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(l_music_options)
                        .addGap(66, 66, 66))
                    .addGroup(p_musicLayout.createSequentialGroup()
                        .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_artist)
                            .addComponent(l_album)
                            .addComponent(l_year))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p_musicLayout.createSequentialGroup()
                        .addComponent(l_music)
                        .addGap(5, 5, 5)
                        .addComponent(t_music)))
                .addContainerGap())
        );
        p_musicLayout.setVerticalGroup(
            p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                .addComponent(l_atual_music)
                .addGap(13, 13, 13)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_music)
                    .addComponent(t_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_pause, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_volume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_q_volume)
                .addGap(18, 18, 18)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_artist)
                    .addComponent(t_artist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_album)
                    .addComponent(t_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_year)
                    .addComponent(t_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_music_options)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_remove_music)
                    .addComponent(b_move_music))
                .addGap(19, 19, 19))
        );

        painel_lista.setViewportView(lista_playlists);

        l_list_playlists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/star_full.png"))); // NOI18N
        l_list_playlists.setText("Playlists");

        l_list_musics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/music_note.png"))); // NOI18N
        l_list_musics.setText("Músicas da Playlist");

        jScrollPane1.setViewportView(lista_musicas);

        javax.swing.GroupLayout p_list_musicLayout = new javax.swing.GroupLayout(p_list_music);
        p_list_music.setLayout(p_list_musicLayout);
        p_list_musicLayout.setHorizontalGroup(
            p_list_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_list_musicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_list_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_lista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_list_musicLayout.createSequentialGroup()
                        .addGroup(p_list_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_list_playlists)
                            .addComponent(l_list_musics))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        p_list_musicLayout.setVerticalGroup(
            p_list_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_list_musicLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(l_list_playlists)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_list_musics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        m_options.setText("Opções");

        mI_add_music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/music_note.png"))); // NOI18N
        mI_add_music.setText("Adicionar Música");
        mI_add_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_add_musicActionPerformed(evt);
            }
        });
        m_options.add(mI_add_music);

        mI_remove_music.setText("Remover Música");
        mI_remove_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_remove_musicActionPerformed(evt);
            }
        });
        m_options.add(mI_remove_music);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh_16.png"))); // NOI18N
        jMenuItem1.setText("Mover Música");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        m_options.add(jMenuItem1);

        mI_add_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/star_full.png"))); // NOI18N
        mI_add_playlist.setText("Adicionar Playlist");
        mI_add_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_add_playlistActionPerformed(evt);
            }
        });
        m_options.add(mI_add_playlist);

        mI_remove_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/star_empty.png"))); // NOI18N
        mI_remove_playlist.setText("Remover Playlist");
        mI_remove_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_remove_playlistActionPerformed(evt);
            }
        });
        m_options.add(mI_remove_playlist);

        mI_promove_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_male_user.png"))); // NOI18N
        mI_promove_user.setText("Promover Usuário");
        mI_promove_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_promove_userActionPerformed(evt);
            }
        });
        m_options.add(mI_promove_user);

        mI_add_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_male_user.png"))); // NOI18N
        mI_add_user.setText("Adicionar Usuário");
        mI_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_add_userActionPerformed(evt);
            }
        });
        m_options.add(mI_add_user);

        mI_remove_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove_male_user.png"))); // NOI18N
        mI_remove_user.setText("Remover Usuário");
        mI_remove_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_remove_userActionPerformed(evt);
            }
        });
        m_options.add(mI_remove_user);

        barra_menu.add(m_options);

        o_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shut_down_16.png"))); // NOI18N
        o_exit.setText("Sair");
        o_exit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                o_exitMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        o_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o_exitMouseClicked(evt);
            }
        });
        o_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_exitActionPerformed(evt);
            }
        });
        barra_menu.add(o_exit);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(p_list_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p_music, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_list_music, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_playActionPerformed

    private void b_remove_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_remove_musicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_remove_musicActionPerformed

    private void b_move_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_move_musicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_move_musicActionPerformed

    private void o_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_exitActionPerformed

    }//GEN-LAST:event_o_exitActionPerformed

    private void o_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o_exitMouseClicked
    System.exit(0);
    dispose();
    }//GEN-LAST:event_o_exitMouseClicked

    private void o_exitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_o_exitMenuSelected

    }//GEN-LAST:event_o_exitMenuSelected

    private void mI_add_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_add_musicActionPerformed
        AdicionarMusicaUserVIPAdmin amuva = new AdicionarMusicaUserVIPAdmin();
        amuva.setVisible(true);
    }//GEN-LAST:event_mI_add_musicActionPerformed

    private void mI_remove_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_remove_musicActionPerformed
        RemoveMusicaUserVIPAdmin rmuva = new RemoveMusicaUserVIPAdmin();
        rmuva.setVisible(true);
    }//GEN-LAST:event_mI_remove_musicActionPerformed

    private void mI_add_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_add_playlistActionPerformed
        AdicionarPlaylist ap = new AdicionarPlaylist();
        ap.setVisible(true);
    }//GEN-LAST:event_mI_add_playlistActionPerformed

    private void mI_remove_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_remove_playlistActionPerformed
        RemovePlaylist rp = new RemovePlaylist();
        rp.setVisible(true);
    }//GEN-LAST:event_mI_remove_playlistActionPerformed

    private void mI_promove_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_promove_userActionPerformed
        PromoveUsuario pu = new PromoveUsuario();
        pu.setVisible(true);
    }//GEN-LAST:event_mI_promove_userActionPerformed

    private void mI_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_add_userActionPerformed
        AdicionarUsuario au = new AdicionarUsuario();
        au.setVisible(true);
    }//GEN-LAST:event_mI_add_userActionPerformed

    private void mI_remove_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_remove_userActionPerformed
        RemoveUsuario ru = new RemoveUsuario();
        ru.setVisible(true);
    }//GEN-LAST:event_mI_remove_userActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MoverMusica mm = new MoverMusica();
        mm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_move_music;
    private javax.swing.JButton b_pause;
    private javax.swing.JButton b_play;
    private javax.swing.JButton b_remove_music;
    private javax.swing.JButton b_stop;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_album;
    private javax.swing.JLabel l_artist;
    private javax.swing.JLabel l_atual_music;
    private javax.swing.JLabel l_list_musics;
    private javax.swing.JLabel l_list_playlists;
    private javax.swing.JLabel l_music;
    private javax.swing.JLabel l_music_options;
    private javax.swing.JLabel l_q_volume;
    private javax.swing.JLabel l_volume;
    private javax.swing.JLabel l_year;
    private javax.swing.JList<String> lista_musicas;
    private javax.swing.JList<String> lista_playlists;
    private javax.swing.JMenuItem mI_add_music;
    private javax.swing.JMenuItem mI_add_playlist;
    private javax.swing.JMenuItem mI_add_user;
    private javax.swing.JMenuItem mI_promove_user;
    private javax.swing.JMenuItem mI_remove_music;
    private javax.swing.JMenuItem mI_remove_playlist;
    private javax.swing.JMenuItem mI_remove_user;
    private javax.swing.JMenu m_options;
    private javax.swing.JMenu o_exit;
    private javax.swing.JPanel p_list_music;
    private javax.swing.JPanel p_music;
    private javax.swing.JScrollPane painel_lista;
    private javax.swing.JSlider s_volume;
    private javax.swing.JTextField t_album;
    private javax.swing.JTextField t_artist;
    private javax.swing.JTextField t_music;
    private javax.swing.JTextField t_year;
    // End of variables declaration//GEN-END:variables
}
