/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediaplayer;

/**
 *
 * @author gisleude
 */
public class JanelaUser extends javax.swing.JFrame {

    /**
     * Creates new form JanelaUser
     */
    public JanelaUser() {
        initComponents();
        this.l_q_volume.setText(Integer.toString(this.s_volume.getValue())+"%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_music = new javax.swing.JPanel();
        l_music = new javax.swing.JLabel();
        l_artist = new javax.swing.JLabel();
        l_album = new javax.swing.JLabel();
        l_year = new javax.swing.JLabel();
        t_music = new javax.swing.JTextField();
        t_artist = new javax.swing.JTextField();
        t_album = new javax.swing.JTextField();
        t_year = new javax.swing.JTextField();
        s_volume = new javax.swing.JSlider();
        l_volume = new javax.swing.JLabel();
        b_play = new javax.swing.JButton();
        b_pause = new javax.swing.JButton();
        b_stop = new javax.swing.JButton();
        l_q_volume = new javax.swing.JLabel();
        l_music_options = new javax.swing.JLabel();
        b_remove_music = new javax.swing.JButton();
        l_atual_music = new javax.swing.JLabel();
        p_list_music = new javax.swing.JPanel();
        painel_lista = new javax.swing.JScrollPane();
        lista_musicas = new javax.swing.JList<>();
        l_list_musics = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        barra_menu = new javax.swing.JMenuBar();
        m_options = new javax.swing.JMenu();
        mI_sub_vip = new javax.swing.JMenuItem();
        mI_sub_admin = new javax.swing.JMenuItem();
        mI_add_music = new javax.swing.JMenuItem();
        mI_remove_music = new javax.swing.JMenuItem();
        o_exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediaPlayer - Free User");
        setResizable(false);

        l_music.setText("Música:");

        l_artist.setText("Artista:");

        l_album.setText("Albúm:");

        l_year.setText("Ano:");

        t_music.setEditable(false);

        t_artist.setEditable(false);

        t_album.setEditable(false);

        t_year.setEditable(false);

        l_volume.setText("Volume:");

        b_play.setText("Play");
        b_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_playActionPerformed(evt);
            }
        });

        b_pause.setText("Pause");

        b_stop.setText("Parar");

        l_music_options.setText("Opções para a música");

        b_remove_music.setText("Remover da Lista");

        l_atual_music.setText("Música Atual");

        javax.swing.GroupLayout p_musicLayout = new javax.swing.GroupLayout(p_music);
        p_music.setLayout(p_musicLayout);
        p_musicLayout.setHorizontalGroup(
            p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_musicLayout.createSequentialGroup()
                .addComponent(l_volume)
                .addGap(3, 3, 3)
                .addComponent(s_volume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(p_musicLayout.createSequentialGroup()
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_musicLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_album, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_artist)
                            .addComponent(t_year, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_musicLayout.createSequentialGroup()
                        .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_artist)
                            .addComponent(l_album)
                            .addComponent(l_year))
                        .addGap(3, 3, 3)))
                .addContainerGap())
            .addGroup(p_musicLayout.createSequentialGroup()
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_musicLayout.createSequentialGroup()
                        .addComponent(b_play, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_musicLayout.createSequentialGroup()
                        .addComponent(l_music)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_music, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                        .addComponent(l_q_volume)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                        .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_musicLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(b_remove_music))
                            .addComponent(l_music_options))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                        .addComponent(l_atual_music)
                        .addGap(87, 87, 87))))
        );
        p_musicLayout.setVerticalGroup(
            p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_musicLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(l_atual_music)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_music)
                    .addComponent(t_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_play)
                    .addComponent(b_pause)
                    .addComponent(b_stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_volume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_q_volume)
                .addGap(35, 35, 35)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_artist)
                    .addComponent(t_artist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_album)
                    .addComponent(t_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_year)
                    .addComponent(t_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_music_options)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_remove_music)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        painel_lista.setViewportView(lista_musicas);

        l_list_musics.setText("Lista de Músicas");

        javax.swing.GroupLayout p_list_musicLayout = new javax.swing.GroupLayout(p_list_music);
        p_list_music.setLayout(p_list_musicLayout);
        p_list_musicLayout.setHorizontalGroup(
            p_list_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_list_musicLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(l_list_musics)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_list_musicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        p_list_musicLayout.setVerticalGroup(
            p_list_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_list_musicLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(l_list_musics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_lista)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        m_options.setText("Opções");

        mI_sub_vip.setText("Virar Usuário VIP");
        mI_sub_vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_sub_vipActionPerformed(evt);
            }
        });
        m_options.add(mI_sub_vip);

        mI_sub_admin.setText("Virar Administrador");
        m_options.add(mI_sub_admin);

        mI_add_music.setText("Adicionar Música");
        m_options.add(mI_add_music);

        mI_remove_music.setText("Remover Música");
        m_options.add(mI_remove_music);

        barra_menu.add(m_options);

        o_exit.setText("Sair");
        barra_menu.add(o_exit);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(p_list_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addComponent(p_music, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(p_list_music, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mI_sub_vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_sub_vipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mI_sub_vipActionPerformed

    private void b_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_pause;
    private javax.swing.JButton b_play;
    private javax.swing.JButton b_remove_music;
    private javax.swing.JButton b_stop;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_album;
    private javax.swing.JLabel l_artist;
    private javax.swing.JLabel l_atual_music;
    private javax.swing.JLabel l_list_musics;
    private javax.swing.JLabel l_music;
    private javax.swing.JLabel l_music_options;
    private javax.swing.JLabel l_q_volume;
    private javax.swing.JLabel l_volume;
    private javax.swing.JLabel l_year;
    private javax.swing.JList<String> lista_musicas;
    private javax.swing.JMenuItem mI_add_music;
    private javax.swing.JMenuItem mI_remove_music;
    private javax.swing.JMenuItem mI_sub_admin;
    private javax.swing.JMenuItem mI_sub_vip;
    private javax.swing.JMenu m_options;
    private javax.swing.JMenu o_exit;
    private javax.swing.JPanel p_list_music;
    private javax.swing.JPanel p_music;
    private javax.swing.JScrollPane painel_lista;
    private javax.swing.JSlider s_volume;
    private javax.swing.JTextField t_album;
    private javax.swing.JTextField t_artist;
    private javax.swing.JTextField t_music;
    private javax.swing.JTextField t_year;
    // End of variables declaration//GEN-END:variables
}
