/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package mediaplayer;

import model.Usuario;
import conexaoDb.ConexaoDb;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gisleude
 */
public class Login extends javax.swing.JFrame {

    ConexaoDb conecta = new ConexaoDb(); // Variavel global de conexao

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conecta.conexao(); // chamada do metodo de conexão
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_login = new javax.swing.JLabel();
        t_user = new javax.swing.JTextField();
        l_user = new javax.swing.JLabel();
        l_senha = new javax.swing.JLabel();
        t_senha = new javax.swing.JPasswordField();
        b_login = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        l_register = new javax.swing.JLabel();
        l_userName = new javax.swing.JLabel();
        t_userName = new javax.swing.JTextField();
        l_userSenha = new javax.swing.JLabel();
        t_userSenha = new javax.swing.JPasswordField();
        t_userEmail = new javax.swing.JTextField();
        l_userEmail = new javax.swing.JLabel();
        t_confirmSenha = new javax.swing.JPasswordField();
        l_confirmSenha = new javax.swing.JLabel();
        b_register = new javax.swing.JButton();
        c_userNivel = new javax.swing.JComboBox<>();
        l_userNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Media Player");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        l_login.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        l_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lock-icon.png"))); // NOI18N
        l_login.setText("Login");

        t_user.setToolTipText("Coloque aqui seu usuario");
        t_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_userActionPerformed(evt);
            }
        });

        l_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        l_user.setText("Usuário");

        l_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/key_16.png"))); // NOI18N
        l_senha.setText("Senha");

        t_senha.setToolTipText("Coloque aqui a sua senha");
        t_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_senhaActionPerformed(evt);
            }
        });

        b_login.setText("Entrar");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        b_cancel.setText("Cancelar");
        b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cancelMouseClicked(evt);
            }
        });
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(l_login))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(l_senha)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_user, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addComponent(t_senha))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(l_user)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_login)
                .addGap(18, 18, 18)
                .addComponent(l_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_login)
                    .addComponent(b_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        l_register.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        l_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_male_user_64.png"))); // NOI18N
        l_register.setText("Registrar");

        l_userName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        l_userName.setText("Usuário");

        t_userName.setToolTipText("Coloque aqui o seu usuário");
        t_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_userNameActionPerformed(evt);
            }
        });

        l_userSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/key_16.png"))); // NOI18N
        l_userSenha.setText("Senha");

        t_userSenha.setToolTipText("Coloque aqui a sua senha");

        t_userEmail.setToolTipText("Coloque aqui o seu email.");

        l_userEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/yellow_mail_16.png"))); // NOI18N
        l_userEmail.setText("E-mail");

        t_confirmSenha.setToolTipText("Confirme a sua senha.");

        l_confirmSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/key_16.png"))); // NOI18N
        l_confirmSenha.setText("Confirmar Senha");

        b_register.setText("Registrar");
        b_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registerActionPerformed(evt);
            }
        });

        c_userNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Usuário VIP", "Administrador" }));
        c_userNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_userNivelActionPerformed(evt);
            }
        });

        l_userNivel.setText("Nivel de Acesso");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(l_userName))
                                .addComponent(t_confirmSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(l_confirmSenha))
                                .addComponent(t_userEmail)
                                .addComponent(t_userSenha)
                                .addComponent(t_userName)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(l_userNivel))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(l_userEmail))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(l_userSenha))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(l_register))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(c_userNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(b_register, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_register)
                .addGap(18, 18, 18)
                .addComponent(l_userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_userEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_userSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_userSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(l_confirmSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_confirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_userNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_userNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_register)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void t_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_userActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_t_userActionPerformed

  private void t_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_senhaActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_t_senhaActionPerformed

  private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
      conecta.executaSQL("SELECT user_name, user_email, user_password, user_nivel FROM usuario");
      String strPassword = new String(t_senha.getPassword());
      String strUser = new String(t_user.getText());
      if (strUser.trim().equals("") || strPassword.trim().equals("")) {
          JOptionPane.showMessageDialog(rootPane, "Espaços obrigatórios sem preenchimento.");
      } else {
          try {
              while (conecta.rs.next()) {
                  if (strUser.equals(conecta.rs.getString(1)) && strPassword.equals(conecta.rs.getString(3))) {
                      Usuario usuario = new Usuario(conecta.rs.getString(1), conecta.rs.getString(2), conecta.rs.getString(3), Integer.parseInt(conecta.rs.getString(4)));
                      // selecionando tipo de janela a ser exibida pelo nivel de usuario
                      if (Integer.parseInt(conecta.rs.getString(4)) == 1) {
                          JanelaUser ju = new JanelaUser();
                          ju.setUsuario(usuario);
                          ju.setVisible(true);
                          dispose();
                      } else if (Integer.parseInt(conecta.rs.getString(4)) == 2) {
                          JanelaUserVIP juv = new JanelaUserVIP();
                          juv.setUsuario(usuario);
                          juv.setVisible(true);
                          dispose();
                      }
                      if (Integer.parseInt(conecta.rs.getString(4)) == 3) {
                          JanelaAdmin ja = new JanelaAdmin();
                          ja.setUsuario(usuario);
                          ja.setVisible(true);
                          dispose();
                      }
                  } else if (strUser.equals(conecta.rs.getString(1)) && !strPassword.equals(conecta.rs.getString(3))) {
                      // Se não achar usuario no banco de dados
                      JOptionPane.showMessageDialog(rootPane, "Usuário ou Senha incorretos.");
                  }
              }
          } catch (SQLException ex) {
              Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
  }//GEN-LAST:event_b_loginActionPerformed

  private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
      conecta.desconecta();
      System.exit(0);
  }//GEN-LAST:event_b_cancelActionPerformed

  private void t_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_userNameActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_t_userNameActionPerformed

  private void b_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registerActionPerformed
      try {
          // Registrando pessoa no banco de dados
          PreparedStatement pst = conecta.conn.prepareStatement("insert into usuario (user_name,user_email,user_password,user_nivel)values(?,?,?,?)"); // passagem de parametros para a inserção
          PreparedStatement pst_playlist = conecta.conn.prepareStatement("insert into playlist(name_playlist,id_user_playlist)");
          String strPassword = new String(t_userSenha.getPassword());
          String strConfirmPassword = new String(t_confirmSenha.getPassword());

          if (t_userName.getText().trim().equals("") || t_userEmail.getText().trim().equals("") || strPassword.trim().equals("") || strConfirmPassword.trim().equals("")) {
              JOptionPane.showMessageDialog(rootPane, "Espaços obrigatórios sem preenchimento.");
          } else if (strPassword.equals(strConfirmPassword)) { // Verificando se as senhas conferem
              if (c_userNivel.getSelectedItem() == c_userNivel.getItemAt(0)) { // Se for um usuário normal
                  pst.setString(1, t_userName.getText());
                  pst.setString(2, t_userEmail.getText());
                  pst.setString(3, strPassword);
                  pst.setString(4, "1");
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "Registrado com sucesso");
                  Login newLogin = new Login();
                  newLogin.setVisible(true);
                  dispose();
              } else if (c_userNivel.getSelectedItem() == c_userNivel.getItemAt(1)) { // Se for um usuario VIP
                  Usuario user = new Usuario(t_userName.getText(), t_userEmail.getText(), strPassword, 2);
                  TelaCodigoVIP codigovip = new TelaCodigoVIP(); // Criar tela que pede código VIP
                  codigovip.user = user; // Passando usuário para proxima tela
                  dispose(); // Fechando tela de login
                  codigovip.setVisible(true); // Abrindo tela de Codigo VIP
              } else if (c_userNivel.getSelectedItem() == c_userNivel.getItemAt(2)) {
                  Usuario user = new Usuario(t_userName.getText(), t_userEmail.getText(), strPassword, 3);
                  TelaCodigoAdmin codigoadmin = new TelaCodigoAdmin();
                  codigoadmin.user = user;
                  dispose();
                  codigoadmin.setVisible(true);
              }
          } else { // Se as senhas não conferem
              JOptionPane.showMessageDialog(rootPane, "As senhas não conferem.");
          }
      } catch (SQLException ex) {
          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(rootPane, "Erro na inserção!\n Erro:" + ex);
      }
  }//GEN-LAST:event_b_registerActionPerformed

  private void c_userNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_userNivelActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_c_userNivelActionPerformed

  private void b_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancelMouseClicked

  }//GEN-LAST:event_b_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_login;
    private javax.swing.JButton b_register;
    private javax.swing.JComboBox<String> c_userNivel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l_confirmSenha;
    private javax.swing.JLabel l_login;
    private javax.swing.JLabel l_register;
    private javax.swing.JLabel l_senha;
    private javax.swing.JLabel l_user;
    private javax.swing.JLabel l_userEmail;
    private javax.swing.JLabel l_userName;
    private javax.swing.JLabel l_userNivel;
    private javax.swing.JLabel l_userSenha;
    private javax.swing.JPasswordField t_confirmSenha;
    private javax.swing.JPasswordField t_senha;
    private javax.swing.JTextField t_user;
    private javax.swing.JTextField t_userEmail;
    private javax.swing.JTextField t_userName;
    private javax.swing.JPasswordField t_userSenha;
    // End of variables declaration//GEN-END:variables
}
